### ISSUE TITLE
pyenchant: I am no longer actively maintaining this project.

### ISSUE THREAD

**Issue by Sandy4321** [chiphuyen/sotawhat#7]
pyenchant is absolet, can you use another package pls
https://github.com/rfk/pyenchant

it gives the error for installation on windows 
E:\AAA_new_Lenovo_start_sep_22_2018\scraping_web\Arxive_papers_oct5\sotawhat-master\sotawhat-master>pip install pyenchant
Collecting pyenchant
  Downloading https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 951kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sndr\AppData\Local\Temp\pip-install-ik9f5dml\pyenchant\setup.py", line 212, in <module>
        import enchant
      File "C:\Users\sndr\AppData\Local\Temp\pip-install-ik9f5dml\pyenchant\enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "C:\Users\sndr\AppData\Local\Temp\pip-install-ik9f5dml\pyenchant\enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\sndr\AppData\Local\Temp\pip-install-ik9f5dml\pyenchant\

**Comment by Sandy4321** [comment]
and from https://www.abisource.com/download/
![image](https://user-images.githubusercontent.com/11426119/46539912-cec4a700-c885-11e8-9143-a0d395e34276.png)

**Comment by Sandy4321** [comment]
anaconda also have only for linux
https://anaconda.org/search?q=pyenchant

**Comment by Sandy4321** [comment]
did you managed to do this?

**Comment by Sandy4321** [comment]
hopefully soon

**Comment by LeenaShekhar** [comment]
If requirement is to just check whether the work is an English word or not then you can use NLTK itself. You can use the function below to check that. 

<code>
from nltk.corpus import words as nltk_words

NLTK_DICT = dict.fromkeys(nltk_words.words(), None)

def is_english_word(word):
    try:
        x = [word]
        return True
    except KeyError:
        return False

</code>

**Comment by LeenaShekhar** [comment]
If requirement is to just check whether the work is an English word or not then you can use NLTK itself. You can use the function below to check that. 

<code>
from nltk.corpus import words as nltk_words

NLTK_DICT = dict.fromkeys(nltk_words.words(), None)

def is_english_word(word): 

    try:  
        x = [word]  
        return True  
    except KeyError:  
        return False  

</code>

**Comment by Sandy4321** [comment]
thanks
can you check code this way?

**Comment by Sandy4321** [comment]
can you changer code this way?

**Comment by chiphuyen** [comment]
Switched to pyspellchecker. Thanks!
